version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Corvus1234
      MYSQL_DATABASE: biblioteca_methaphorce
    healthcheck:
      # Checks if the MySQL server is responsive.
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pCorvus1234"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3310:3310"
    volumes:
      - mysql-data:/var/lib/mysql

  usuarios-app:
    build: .
    container_name: usuarios-app-container
    restart: on-failure
    depends_on: 
      mysql-db:
        condition: service_healthy
    ports:
      - "8081:8081"

volumes:
  mysql-data:
